#!/bin/bash
# Usage: ./run_CTSP class name max_trials runs [ optimum ]

if [ -z "$4" ]; then
    echo "./run_CTSP classs name max_trials runs [ optimum ]"
    exit
fi

lkh="./LKH"
class=$1
name=$2
max_trials=$3
runs=$4
optimum=$5
par=TMP/$name.pid$$.par

mkdir -p TOURS
mkdir -p TOURS/$class
mkdir -p TMP

echo "SPECIAL" > $par
echo "PROBLEM_FILE = $name.ctsp" >> $par
echo "INITIAL_TOUR_ALGORITHM = CTSP" >> $par
echo "MAX_TRIALS = $max_trials" >> $par
echo "RUNS = $runs" >> $par
# echo "TOUR_FILE = TOURS/$class/$name.$.tour" >> $par
echo "TRACE_LEVEL = 1" >> $par
echo "SEED = 0" >> $par

if [ -n "$optimum" ]; then
    echo "OPTIMUM = $optimum" >> $par
fi

if false; then
    for FILE in `ls TOURS/$class/$name.*.tour` ;
    do
        echo "INITIAL_TOUR_FILE = $FILE" >> $par
        break
    done
fi

$lkh $par

/bin/rm -f $par
